# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FileMapper < Formula
  desc "file-mapper: Combines tree and cat in one CLI for recursive project mapping and file content viewing."
  homepage "https://github.com/sky93/file-mapper"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sky93/file-mapper/releases/download/v0.0.10/file-mapper_0.0.10_darwin_amd64.tar.gz"
      sha256 "2db3935743db7ebe5459ae404fa3665f51b78833b2b3f53f64c6855fc4b5d5c9"

      def install
        # This is how the formula installs the binary
        bin.install "file-mapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sky93/file-mapper/releases/download/v0.0.10/file-mapper_0.0.10_darwin_arm64.tar.gz"
      sha256 "ae97b3e651a085a3e0e0999162f347b3bf19c9048320f9c90c0709ba20668628"

      def install
        # This is how the formula installs the binary
        bin.install "file-mapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sky93/file-mapper/releases/download/v0.0.10/file-mapper_0.0.10_linux_amd64.tar.gz"
        sha256 "f600444462de9d772ded1f43c9281e5f3849f6b99983264b9c19a515fd2e7b19"

        def install
          # This is how the formula installs the binary
          bin.install "file-mapper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sky93/file-mapper/releases/download/v0.0.10/file-mapper_0.0.10_linux_arm64.tar.gz"
        sha256 "369704f0f543bbe43c8327470bdef11b0ad251c3bb9c3c72cf40946381497cca"

        def install
          # This is how the formula installs the binary
          bin.install "file-mapper"
        end
      end
    end
  end
end
