# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FileMapper < Formula
  desc "file-mapper: Combines tree and cat in one CLI for recursive project mapping and file content viewing."
  homepage "https://github.com/sky93/file-mapper"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sky93/file-mapper/releases/download/v0.0.9/file-mapper_0.0.9_darwin_amd64.tar.gz"
      sha256 "97ebd378004026038b3d922c82d0aba5d17cbd0bae566972c4ba7afd9b3897a8"

      def install
        # This is how the formula installs the binary
        bin.install "file-mapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sky93/file-mapper/releases/download/v0.0.9/file-mapper_0.0.9_darwin_arm64.tar.gz"
      sha256 "64498563f66fe89d0d47f215f648ca3e6237a19e75550d901a0586360b92e0a5"

      def install
        # This is how the formula installs the binary
        bin.install "file-mapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sky93/file-mapper/releases/download/v0.0.9/file-mapper_0.0.9_linux_amd64.tar.gz"
        sha256 "38c4113cbcdd35021ca2b53810ad894df43e702b74bce3748196149186e70ba4"

        def install
          # This is how the formula installs the binary
          bin.install "file-mapper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sky93/file-mapper/releases/download/v0.0.9/file-mapper_0.0.9_linux_arm64.tar.gz"
        sha256 "bd321baf7c70588f5f2cbd5b4c40f6e1a9317e803edcb52a0f086fce69a1e1b3"

        def install
          # This is how the formula installs the binary
          bin.install "file-mapper"
        end
      end
    end
  end
end
